-- SELECT * FROM users;


-- \dt

-- Schema |      Name      | Type  | Owner
-- --------+----------------+-------+--------
--  public | chats          | table | meetai
--  public | meeting_chunks | table | meetai
--  public | meetings       | table | meetai
--  public | messages       | table | meetai
--  public | users          | table | meetai


 SELECT column_name
 FROM information_schema.columns
WHERE table_name = 'messages';


-- select * from meetings