"""
chunk_store.py
--------------
Persists transcription chunks to the `meeting_chunks` Postgres table.

Embeddings are computed by the shared singleton in ``src.infra.embeddings``
(BAAI/bge-m3 via MLX fp16) so the model is loaded only once per worker.

Design decisions
----------------
- DB writes are fire-and-forget at the pipeline level: failures here are
  logged but never propagate to crash the audio pipeline.
- Each chunk gets a fresh UUID *before* the DB write, so the generated IDs
  are returned to the caller even when the transaction itself fails. The
  topic processor uses these IDs to reference exact chunks.
- ``persist()`` returns the persisted chunks as ``PersistedChunk`` Pydantic
  records — this is the single source of truth for what flowed into the DB
  during a window flush.
"""
from __future__ import annotations
import logging
from typing import List
import asyncpg
from src.core.topic_models import PersistedChunk
from src.infra.embeddings import embed_texts_async

logger = logging.getLogger(__name__)

def _coerce_speakers(raw) -> List[str]:
    if not raw:
        return []
    if isinstance(raw, str):
        return [raw]
    return list(raw)

class ChunkStore:
    """
    Writes flushed chunks to `meeting_chunks` in Postgres with BGE-M3 embeddings.

    Parameters
    ----------
    meeting_id : int  # BIGINT
        The meeting row ID from the main app DB.
    user_id : int  # BIGINT
        The user row ID from the main app DB.
    db_pool : asyncpg.Pool
        Shared connection pool — created once by the worker and passed in.
    """
    def __init__(self, meeting_id: int, user_id: int, db_pool: asyncpg.Pool) -> None:
        self._meeting_id = meeting_id
        self._user_id = user_id
        self._pool = db_pool

    async def persist(self, chunks: List[dict]) -> List[PersistedChunk]:
        """
        Embed *chunks* and insert them into `meeting_chunks`.

        chunk_id is now BIGSERIAL — generated by Postgres and retrieved via
        RETURNING. Because IDs are unknown before the write, a failure returns
        an empty list and nothing is returned to the caller.
        """
        if not chunks:
            return []

        # Freeze metadata up-front (minus chunk_id — Postgres owns that now)
        prepared = [
            dict(
                text=chunk["text"],
                start=float(chunk.get("start") or 0.0),
                end=float(chunk.get("end") or 0.0),
                speakers=_coerce_speakers(chunk.get("speakers")),
            )
            for chunk in chunks
        ]

        try:
            texts = [c["text"] for c in prepared]
            embeddings = await embed_texts_async(texts)
            persisted = await self._write_to_db(prepared, embeddings)
            logger.debug(
                "ChunkStore: persisted %d chunks for meeting_id=%s",
                len(persisted),
                self._meeting_id,
            )
            return persisted
        except Exception:
            logger.exception(
                "ChunkStore: failed to persist %d chunks for meeting_id=%s",
                len(prepared),
                self._meeting_id,
            )
            return []

    async def _write_to_db(
        self,
        prepared: List[dict],
        embeddings: List[List[float]],
    ) -> List[PersistedChunk]:
        """INSERT all chunks in a single transaction, returning generated IDs."""
        sql = """
            INSERT INTO meeting_chunks
                (meeting_id, user_id, text, speakers,
                 start_time, end_time, embedding)
            VALUES
                ($1::bigint, $2::bigint, $3, $4, $5, $6, $7::vector)
            RETURNING chunk_id
        """
        persisted: List[PersistedChunk] = []

        async with self._pool.acquire() as conn:
            async with conn.transaction():
                for chunk, emb in zip(prepared, embeddings):
                    emb_str = "[" + ",".join(f"{v:.8f}" for v in emb) + "]"
                    row = await conn.fetchrow(
                        sql,
                        self._meeting_id,
                        self._user_id,
                        chunk["text"],
                        chunk["speakers"],
                        chunk["start"],
                        chunk["end"],
                        emb_str,
                    )
                    persisted.append(
                        PersistedChunk(
                            chunk_id=row["chunk_id"],  # int from BIGSERIAL
                            text=chunk["text"],
                            start=chunk["start"],
                            end=chunk["end"],
                            speakers=chunk["speakers"],
                        )
                    )

        return persisted