version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"   # Vite default dev server port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Needed for file watching in Docker on some OS
      - HOST=0.0.0.0   # <- This line is key
      - VITE_AUTH_URL=http://localhost:4010
    command: npm run dev

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"  # Serve production on port 80
    depends_on:
      - web
